### ISSUE TITLE
"The CM Storm Alcor mouse is not connected or couldn't be found."

### ISSUE THREAD

**Issue by ghost** [thelink2012/cmalcor#3]
![not_connected](https://cloud.githubusercontent.com/assets/24739792/21463527/d206b79e-c96a-11e6-9164-3b0c6accb1e4.png)

**Comment by thelink2012** [comment]
Could you replace [this line](https://github.com/thelink2012/cmalcor/blob/master/cmalcor/src/capi.cc#L45) with simply `return HidDevice::ScanForDevice(0x2516, 0x28);`, recompile, and see if that works?

No worries if you aren't into this kind of stuff, I can send the binary with the proper changes and you feedback me if it works.

**Comment by ghost** [comment]
Since you're asking me to do it, I assume you can't do it yourself right now. I installed VS and changed that line. Now you just have to tell me how to execute the batch script so I can compile it. I can't figure that out. I'm not a programmer unfortunately, I'm just a guy who bought a CM Alcor mouse. All I can say is that VS seems overly complicated for me.

**Comment by thelink2012** [comment]
https://dl.dropboxusercontent.com/u/35476123/cmalcor.zip

Replace this dll with the dll in the directory you have extracted this thing... if this makes sense.

**Comment by ghost** [comment]
It worked. Thanks!
