### ISSUE TITLE
Nothing happens to my mouse after pressing the "Apply" button

### ISSUE THREAD

**Issue by Form4t-Dev** [thelink2012/cmalcor#4]
Hello,
When i try to set a color to my mouse nothing happens after pressing the "Apply" button (software is running as administrator).
The mouse led color doesn't change and there are no errors displayed on the screen.
I'm using the FW 1.2.0 but I've tried with different ones, so I don't think it's a FW problem.

**Comment by dansator** [comment]
If you are on Windows 10, try to run it using Windows 8 compatibility mode

**Comment by Form4t-Dev** [comment]
I've tried but nothing changes.
